version: '3.6'

services:
  berikard-mongo-database:
    container_name: berikard-mongo-database
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
   
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    networks:
      - berikard-mongo-network

  berikard-service:
    container_name: backend
    image: berikard-service
    build:
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ./.env  
    
    volumes:
      - node_modules:/app/berikard-service/node_modules
      - .:/app/berikard-service
    networks:
      - berikard-mongo-network
    depends_on:
      - berikard-mongo-database

  berikard-frontend:
    container_name: frontend
    image: berikard-frontend
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.dev

    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env    
    
    volumes:
      - node_modules:/app/berikard-frontend/node_modules
      - .:/app/berikard-frontend
    networks:
      - berikard-mongo-network
    depends_on:
      - berikard-mongo-database  




volumes:
  node_modules:

networks:
  berikard-mongo-network:
