FROM node:16-alpine

WORKDIR /app/berikard-backend
COPY package.json \
    tsconfig.json \
    nest-cli.json \
    /app/berikard-backend/

RUN npm install
RUN npm run build

ENTRYPOINT [ "node", "dist/src/main" ]